name: supabase-infra

on:
  push:
    branches: [ "main" ]
    paths:
      - "supabase/**"
  workflow_dispatch:

jobs:
  supabase:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno (for Edge Functions)
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # ---- Authenticate with PAT so the CLI won't prompt for DB password ----
      - name: Auth to Supabase (PAT)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        shell: bash
        run: |
          if [ -z "${SUPABASE_ACCESS_TOKEN}" ]; then
            echo "::error::SUPABASE_ACCESS_TOKEN is empty. Add a repo secret with a PAT starting with 'sbp_'."; exit 1
          fi
          supabase login --token "${SUPABASE_ACCESS_TOKEN}"

      # ---- Link to your project using the project ref secret ----
      - name: Link project (non-interactive)
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        shell: bash
        run: |
          if [ -z "${SUPABASE_PROJECT_REF}" ]; then
            echo "::error::SUPABASE_PROJECT_REF is empty. Add a repo secret with your project ref (e.g. jhfvylrqkhebxaxyfcaj)."; exit 1
          fi
          supabase link --project-ref "${SUPABASE_PROJECT_REF}"

      # ---- Apply migrations to the remote DB ----
      - name: DB push (migrations)
        run: supabase db push

      # ---- Optional seed; use stdin for widest CLI compatibility ----
      - name: Seed (optional)
        shell: bash
        run: |
          if [ -f supabase/seed/seed.sql ]; then
            cat supabase/seed/seed.sql | supabase db query
          else
            echo "No seed file found; skipping."
          fi

      # ---- Deploy Edge Functions (if present) ----
      - name: Deploy Edge Functions
        shell: bash
        run: |
          if [ -d supabase/functions/hello-world ]; then
            supabase functions deploy hello-world
          else
            echo "No edge functions to deploy; skipping."
          fi
