
name: supabase-infra
on:
  push:
    branches: [ "main" ]
    paths:
      - "supabase/**"
  workflow_dispatch:

jobs:
  supabase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Supabase CLI
        run: |
          curl -sL https://supabase.io/cli/install | sh
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH

      - name: Link project (requires SUPABASE_ACCESS_TOKEN & project ref in config.toml)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref "$(grep project_id supabase/config.toml | cut -d'=' -f2 | tr -d ' \"')"

      - name: DB push (migrations)
        run: supabase db push

      - name: Seed (optional)
        run: |
          if [ -f supabase/seed/seed.sql ]; then
            supabase db query < supabase/seed/seed.sql
          fi

      - name: Deploy Edge Functions
        run: |
          if [ -d supabase/functions/hello-world ]; then
            supabase functions deploy hello-world
          fi
