name: supabase-infra

on:
  push:
    branches: [ "main" ]
    paths:
      - "supabase/**"
  workflow_dispatch:

jobs:
  supabase:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno (for Edge Functions)
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # 🔐 Auth & Link in one step so PAT is definitely active for link
      - name: Auth + Link (non-interactive)
        shell: bash
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          set -euo pipefail
          if [[ -z "${SUPABASE_ACCESS_TOKEN:-}" ]]; then
            echo "::error::SUPABASE_ACCESS_TOKEN is empty. Add a repo secret with a PAT starting with 'sbp_'."; exit 1
          fi
          if [[ -z "${SUPABASE_PROJECT_REF:-}" ]]; then
            echo "::error::SUPABASE_PROJECT_REF is empty. Add a repo secret with your project ref (e.g. jhfvylrqkhebxaxyfcaj)."; exit 1
          fi

          # Authenticate using PAT (writes to ~/.config/supabase)
          supabase login --token "${SUPABASE_ACCESS_TOKEN}"

          # Confirm login (non-verbose)
          supabase --version

          # Link to your project by ref (no password prompts)
          supabase link --project-ref "${SUPABASE_PROJECT_REF}"

      - name: DB push (migrations)
        run: supabase db push

      - name: Seed (optional)
        shell: bash
        run: |
          set -euo pipefail
          if [[ -f supabase/seed/seed.sql ]]; then
            # Use stdin for widest CLI compatibility
            cat supabase/seed/seed.sql | supabase db query
          else
            echo "No seed file found; skipping."
          fi

      - name: Deploy Edge Functions
        shell: bash
        run: |
          set -euo pipefail
          if [[ -d supabase/functions/hello-world ]]; then
            supabase functions deploy hello-world
          else
            echo "No edge functions to deploy; skipping."
          fi
