name: supabase-infra

on:
  push:
    branches: [ "main" ]
    paths:
      - "supabase/**"
  workflow_dispatch:

jobs:
  supabase:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Make secrets available to all steps; we'll mask the password wherever we echo it
    env:
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno (for Edge Functions)
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Optional: PAT auth (nice-to-have, not required when we pass --password)
      - name: Auth (optional PAT)
        shell: bash
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          set -euo pipefail
          if [[ -n "${SUPABASE_ACCESS_TOKEN:-}" ]]; then
            echo "::add-mask::${SUPABASE_ACCESS_TOKEN}"
            supabase login --token "${SUPABASE_ACCESS_TOKEN}"
          else
            echo "No SUPABASE_ACCESS_TOKEN provided; continuing without PAT."
          fi

      # ✅ Link on every run using DB password (non-interactive, idempotent)
      - name: Link project (DB password; non-interactive)
        shell: bash
        run: |
          set -euo pipefail
          if [[ -z "${SUPABASE_PROJECT_REF:-}" ]]; then
            echo "::error::SUPABASE_PROJECT_REF is empty"; exit 1
          fi
          if [[ -z "${SUPABASE_DB_PASSWORD:-}" ]]; then
            echo "::error::SUPABASE_DB_PASSWORD is empty"; exit 1
          fi
          echo "::add-mask::${SUPABASE_DB_PASSWORD}"
          supabase link \
            --project-ref "${SUPABASE_PROJECT_REF}" \
            --password    "${SUPABASE_DB_PASSWORD}" \
            --workdir     .

      # ✅ Apply migrations — DO NOT pass --project-ref (unsupported for db subcommands)
      - name: DB push (migrations)
        shell: bash
        run: |
          set -euo pipefail
          echo "::add-mask::${SUPABASE_DB_PASSWORD}"
          supabase db push --workdir . --password "${SUPABASE_DB_PASSWORD}"

      # ✅ Seed — also no --project-ref; use stdin for broad CLI compatibility
      - name: Seed (optional)
        if: ${{ hashFiles('supabase/seed/seed.sql') != '' }}
        shell: bash
        run: |
          set -euo pipefail
          echo "::add-mask::${SUPABASE_DB_PASSWORD}"
          cat supabase/seed/seed.sql | supabase db query --workdir . --password "${SUPABASE_DB_PASSWORD}"

      # ✅ Deploy Edge Functions — uses the link context
      - name: Deploy Edge Functions
        shell: bash
        run: |
          set -euo pipefail
          if [[ -d supabase/functions/hello-world ]]; then
            supabase functions deploy hello-world --workdir .
          else
            echo "No edge functions to deploy; skipping."
          fi
